fixed numerous styling issues and removed a lot of placeholder content
d-drozdov/whiz-kids-baseball pull request #15
Opened 2023-01-15 19:21 UTC by jake-rasmussen

2023-01-15 19:23 UTC, jake-rasmussen commented
Neatened up some spacing issues and fixed hydration issues

2023-01-15 20:42 UTC, d-drozdov commented on src/pages/index.tsx
> +      <React.Fragment key={index}>
Do we need to import React bc of this ?

2023-01-15 20:50 UTC, d-drozdov commented on src/pages/index.tsx
> +import MainLayout from "../components/layouts/mainLayout";
Should be "../components/layouts/MainLayout" I believe

2023-01-15 20:50 UTC, d-drozdov commented on src/components/layouts/mainLayout.tsx
> +    <div className="overflow-y-scroll">
Not sure what this is for maybe you can tell me later

2023-01-15 20:51 UTC, d-drozdov requested changes
Just take a look at some of the comments

2023-01-16 14:36 UTC, jake-rasmussen commented on src/pages/index.tsx
> +      <React.Fragment key={index}>
Yes but it's imported already

2023-01-16 16:32 UTC, d-drozdov approved these changes
LGTM

2023-01-16 16:32 UTC, merged